"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require('dotenv').config();
const defaults = {
    REDIS_URL: '',
    DATABASE_URL: '',
    YOUTUBE_API_KEY: '',
    NODE_ENV: '',
    FIREBASE_ADMIN_SDK_CONFIG: '',
    FIREBASE_DATABASE_URL: '',
    STRIPE_SECRET_KEY: '',
    VBROWSER_SESSION_SECONDS: 10800,
    VBROWSER_SESSION_SECONDS_LARGE: 86400,
    VM_POOL_RAMP_DOWN_HOURS: '',
    VM_POOL_RAMP_UP_HOURS: '',
    VBROWSER_TAG: '',
    DO_TOKEN: '',
    DO_GATEWAY: '',
    DO_IMAGE: '',
    DO_SSH_KEYS: '',
    HETZNER_TOKEN: '',
    HETZNER_GATEWAY: '',
    HETZNER_SSH_KEYS: '',
    HETZNER_IMAGE: '',
    VM_MANAGER_CONFIG: 'Docker:large:US:0:0,Docker:standard:US:0:0',
    SCW_SECRET_KEY: '',
    SCW_ORGANIZATION_ID: '',
    SCW_GATEWAY: '',
    SCW_IMAGE: '',
    DOCKER_VM_HOST: '',
    DOCKER_VM_HOST_SSH_USER: '',
    DOCKER_VM_HOST_SSH_KEY_BASE64: '',
    RECAPTCHA_SECRET_KEY: '',
    HTTPS: '',
    SSL_KEY_FILE: '',
    SSL_CRT_FILE: '',
    PORT: 8080,
    HOST: '0.0.0.0',
    STATS_KEY: '',
    BETA_USER_EMAILS: '',
    CUSTOM_SETTINGS_HOSTNAME: '',
    STREAM_PATH: '',
    ROOM_CAPACITY: 0,
    ROOM_CAPACITY_SUB: 0,
    BUILD_DIRECTORY: 'build',
    VM_MIN_UPTIME_MINUTES: 0,
    SHARD: undefined,
    SUBSCRIBER_ROOM_LIMIT: 20,
    VMWORKER_PORT: 3100,
    VM_ASSIGNMENT_TIMEOUT: 75,
    DEFAULT_VM_REGION: 'US',
    DISCORD_BOT_TOKEN: '',
    DISCORD_ADMIN_BOT_TOKEN: '',
    DISCORD_ADMIN_BOT_SERVER_ID: '708181150220156929',
    DISCORD_ADMIN_BOT_SUB_ROLE_ID: '722202622345609246',
    MEDIASOUP_SERVER: '',
    TWITCH_PROXY_PATH: '', // Optional, URL of the server that can proxy twitch HLS stream playlists and segments
};
exports.default = Object.assign(Object.assign({}, defaults), process.env);
